name: Daily Telegram Reminder

on:
  schedule:
    - cron: '30 23 * * *'  # 台灣時間 07:30（+8時區 = UTC 23:30）
  workflow_dispatch:

jobs:
  send_reminder:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install requests
        run: pip install requests

      - name: Run send_reminder.py
        run: python send_reminder.py
